# Generated by Django 4.2.2 on 2023-06-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pericia',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
