# Generated by Django 4.2.2 on 2023-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pericia',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='Descrição',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='Publicado',
            new_name='publicado',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
