# Generated by Django 4.2.2 on 2023-06-21 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitepc', '0002_rename_descricao_pericia_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='categoria',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='descrição',
            new_name='Descrição',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='publicado',
            new_name='Publicado',
        ),
        migrations.RenameField(
            model_name='pericia',
            old_name='titulo',
            new_name='Titulo',
        ),
        migrations.AddField(
            model_name='pericia',
            name='Autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
